export const DUST_BUTTON_FADE_DURATION = 0.5;
export const DUST_BUTTON_PARTICLE_DURATION = 2;

export const DUST_BUTTON_PARTICLE_START_PROGRESS =
  DUST_BUTTON_FADE_DURATION /
  (DUST_BUTTON_FADE_DURATION + DUST_BUTTON_PARTICLE_DURATION);
